name: ci-test
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: drama
          path: drama-queen/dist
      - uses: actions/upload-artifact@v3
        with:
          name: queen
          path: queen/build
      - uses: actions/upload-artifact@v3
        with:
          name: queen-v2
          path: queen-v2/build
  docker:
    needs: build
    environment: Main
    if: |
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Drama Image
      - uses: actions/download-artifact@v3
        with:
          name: drama
          path: drama-queen/dist
      - uses: docker/build-push-action@v4
        with:
          context: drama-queen
          push: true
          tags: ddecrulle/drama-queen:${{ github.ref_name }}
        # Queen Image
      - uses: actions/download-artifact@v3
        with:
          name: queen
          path: queen/build

      - uses: docker/build-push-action@v4
        with:
          context: ./queen
          push: true
          tags: ddecrulle/queen:${{ github.ref_name }}
      # Queen V2 Image
      - uses: actions/download-artifact@v3
        with:
          name: queen-v2
          path: queen-v2/build
      - uses: docker/build-push-action@v4
        with:
          context: ./queen-v2
          push: true
          tags: ddecrulle/queen-v2:${{ github.ref_name }}
