name: ci
on:
  push:
    branches:
      - "test-ci"

jobs:
  check_if_version_upgraded:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      github.ref_name == 'main'
    outputs:
      is_upgraded_version: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
      is_drama_upgraded_version: ${{ steps.check-drama.outputs.changed }}
      drama_version: ${{ steps.check-drama.outputs.version }}
      is_queen_upgraded_version: ${{ steps.check-queen.outputs.changed }}
      queen_version: ${{ steps.check-queen.outputs.version }}
      is_queen_v2_upgraded_version: ${{ steps.check-queen-v2.outputs.changed }}
      queen_v2_version: ${{ steps.check-queen-v2.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check if container version has been updated
        id: check
        uses: EndBug/version-check@v2
      - name: Check if drama queen version has been updated
        id: check-drama
        uses: EndBug/version-check@v2
        with:
          file-name: drama-queen/package.json
      - name: Check if queen version has been updated
        id: check-queen
        uses: EndBug/version-check@v2
        with:
          file-name: queen/package.json
      - name: Check if queen-v2 version has been updated
        id: check-queen-v2
        uses: EndBug/version-check@v2
        with:
          file-name: queen-v2/package.json
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'

  echo_check_job:
    needs: check_if_version_upgraded
    runs-on: ubuntu-latest
    steps:
      - name: Log when changed
        if: needs.check_if_version_upgraded.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ needs.check_if_version_upgraded.outputs.commit }}! New version: ${{ needs.check_if_version_upgraded.outputs.version }} (${{ needs.check_if_version_upgraded.outputs.type }})"'

      - name: Log when unchanged
        if: needs.check_if_version_upgraded.outputs.changed == 'false'
        run: 'echo "No version change :/"'


      