name: ci
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    environment: Main
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn
      - name: Copy .env file for drama queen
        env:
          VITE_QUEEN_URL: ${{ vars.VITE_QUEEN_URL }}
          VITE_QUEEN_V2_URL: ${{ vars.VITE_QUEEN_V2_URL }}
        run: |
          cp drama-queen/.env drama-queen/.env.production
          sed -i "s#VITE_QUEEN_URL=#VITE_QUEEN_URL=${VITE_QUEEN_URL}#" drama-queen/.env.production
          sed -i "s#VITE_QUEEN_V2_URL=#VITE_QUEEN_V2_URL=${VITE_QUEEN_V2_URL}#" drama-queen/.env.production
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: drama
          path: drama-queen/dist
      - uses: actions/upload-artifact@v3
        with:
          name: queen
          path: queen/build
      - uses: actions/upload-artifact@v3
        with:
          name: queen-v2
          path: queen-v2/build

  check_if_version_upgraded:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Check if container version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Check if drama queen version has been updated
        id: check-drama
        uses: EndBug/version-check@v2
        with:
          file-name: drama-queen/package.json

      - name: Check if queen version has been updated
        id: check-queen
        uses: EndBug/version-check@v2
        with:
          file-name: queen/package.json

      - name: Check if queen-v2 version has been updated
        id: check-queen-v2
        uses: EndBug/version-check@v2
        with:
          file-name: queen-v2/package.json

  docker_drama:
    needs: check_if_version_upgraded
    environment: Main
    if: needs.check_if_version_upgraded.steps.check-drama.outputs.changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: drama
          path: drama-queen/dist
      - uses: docker/build-push-action@v4
        with:
          context: drama-queen
          push: true
          tags: ddecrulle/drama-queen:${{ needs.check_if_version_upgraded.steps.check-drama.outputs.version }}

  docker_queen:
    needs: check_if_version_upgraded
    environment: Main
    if: needs.check_if_version_upgraded.steps.check-queen.outputs.changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: queen
          path: queen/build
      - uses: docker/build-push-action@v4
        with:
          context: ./queen
          push: true
          tags: ddecrulle/queen:${{ needs.check_if_version_upgraded.steps.check-queen.outputs.version }}

  docker_queen_v2:
    needs: check_if_version_upgraded
    environment: Main
    if: needs.check_if_version_upgraded.steps.check-queen.outputs.changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: queen-v2
          path: queen-v2/build
      - uses: docker/build-push-action@v4
        with:
          context: ./queen-v2
          push: true
          tags: ddecrulle/queen-v2:${{ needs.check_if_version_upgraded.steps.check-queen.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: check_if_version_upgraded
    if: needs.check_if_version_upgraded.steps.check.outputs.changed
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ needs.check_if_version_upgraded.steps.check.outputs.version }}
          tag_name: v${{ needs.check_if_version_upgraded.steps.check.outputs.version }}
          target_commitish: ${{ github.head_ref || github.ref }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
